# Generated by Django 5.2 on 2025-06-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.TextField(blank=True)),
                ('course_init_date', models.DateField()),
                ('course_finish_date', models.DateField()),
                ('course_instructors', models.CharField(max_length=200)),
                ('course_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em Processamento'), ('success', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=10)),
            ],
        ),
    ]
