# Generated by Django 5.2 on 2025-06-07 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
