# Generated by Django 5.2 on 2025-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_funcionario_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
