# Generated by Django 5.2 on 2025-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('nome', models.TextField(max_length=255)),
                ('nif', models.CharField(max_length=100, unique=True)),
                ('endereco', models.TextField(max_length=255)),
                ('representante_legal', models.TextField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
