# Generated by Django 5.2 on 2025-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registrar_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_empresa',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
