# Generated by Django 5.2 on 2025-06-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_registrar_empresa_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrar_Empresa',
        ),
    ]
