# Generated by Django 5.2 on 2025-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_registrar_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecreator',
            name='table_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
